# Nombre del flujo de trabajo 
name: i-haklab-build

# Se ejecutara en cada push a la rama principal y en cada pull request.
on:
  push:
    branches:
      - main
  pull_request:

# MV 
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest 
    steps:
    - name: Install dependencies...
      run: |
        sudo apt update && sudo apt install -y tar
# Permite compartir datos 
    - name: Clone repository
      uses: actions/checkout@v3 
    - name: Filling in home...
      run: tar -zcf  Home.tar.gz  -C  ./.deb/i-haklab  ./home  
    - name: Compilando... 
      run: pwd
    - name: Uploading... 
      uses: actions/upload-artifact@v4 
      with:
         name: Configuraciones  
         path: Home.tar.gz  

    - uses: actions/upload-artifact@v4
      with:
         name: my-artifact
         path: |
            build/i-haklab   
            build/src/libbelow_zero.so 
